---
sudo: required
language: python

env:
  - >
    container_id=$(mktemp)
    distribution=fedora
    version=33

services:
  - docker

before_install:
  - sudo apt-get update

script:
  - ./test/test.sh ${version}
