---
- name: go - install ginkgo cli
  command: go get -u github.com/onsi/ginkgo/ginkgo  
- name: go - install gomega matcher library
  command: go get -u github.com/onsi/gomega/...     # fetches the matcher library